### ISSUE TITLE
add a note about the default scale rule

### ISSUE THREAD

**Issue by rafaeltuelho** [Azure/aca-java-runtimes-workshop#29]
It would be helpful to add a note about the default scale policy used by ACA on the `Scaling` topic:

Ref: https://azure.github.io/Cloud-Native/blog/11-scaling-container-apps/#configuring-aca-scale-rules
> By default, when you deploy a container app, it is set to scale from 0 to 10 replicas. The default scaling rule uses HTTP scaling and defaults to a minimum of 10 concurrent requests per second.

**Comment by sinedied** [comment]
Done, thanks for the suggestion 🙂
