### ISSUE TITLE
Enhancement: Allow user to source a file with all of the required environment variables

### ISSUE THREAD

**Issue by ndalalelis** [Azure/aca-java-runtimes-workshop#4]
A user is asked to set a few environment variables in the beginning of the workshop [here](https://azure.github.io/aca-java-runtimes-workshop/#setting-up-the-environment-variables).  For users that may want to have multiple terminals for the workshop, it may be nice to have the environment variables in a file so that it can be sourced.

```
source aca-environment-setting
```

**Comment by agoncal** [comment]
@sinedied WDYT? We could have such a file and source it from our scripts (`azure.sh` and `deploy.sh`). Would that be a heavy refactoring ?
